### PR TITLE
Allow non-default serial port

### PR DESCRIPTION
**Pull request by suhlig**
The ESP32 [has three serial ports](https://quadmeup.com/arduino-esp32-and-3-hardware-serial-ports/). This allows to connect the SDS011 to a port that is different from the default one, so that we can still print to the default serial port and see what's going on with the SDS011.

So far this was not possible because [`SDS011::setup`](https://github.com/bertmelis/SDS011/blob/b814f617a8f408666fd61ea9f55309360e3492bf/src/SDS011.cpp#L45) [calls `Serial.begin` with default args](https://github.com/espressif/arduino-esp32/blob/37a7fb3d6ada8a9230c96e2df999c95ef10fd4d3/cores/esp32/HardwareSerial.cpp#L33-L53), which also means default pins.

This PR adds an overloaded `SDS011::setup` which accepts arbitrary `rx` and `tx` pins as additional parameters.

An alternative implementation would simply remove the `Serial.begin` call from `SDS011::setup`. I would actually prefer this, as it leaves setup to the caller. On the other hand, it would break existing clients, so I went with the approach in this PR.

I also added an example that showcases the new behaviour.

### CODE REVIEW

**Comment by bertmelis** [comment]
According Travis, the build fails on ESP8266. Should the extra method be guarded by `#ifdef` to limit this to ESP32?

**Comment by suhlig** [comment]
Ah, I overlooked that part. Yes, an `#ifdef` looks like a sensible way to solve that.

Just pushed a fixup commit.

**Comment by suhlig** [comment]
Travis status seems out of sync - the builds are green now.

**Comment by suhlig** [comment]
Hi @bertmelis any chance to merge this? Please note that the Travis checks are actually green; it seems just the reporting back to GH is broken somehow.

**Comment by bertmelis** [comment]
Sorry for the delay. Totally forgot about it.

**Pull request merged**
